### ISSUE TITLE
How to rotate the gaussian splats?

### ISSUE THREAD

**Issue by JanaldoChen** [JonathonLuiten/Dynamic3DGaussians#16]
Hi, everyone!

I want to rotate my pretrained gaussian model, I have rotated the **_xyz** and **_rotation** of gaussian splats, but the rendering results got worse! The problem I guess is that the spherical harmonics (**_featrues_dc** and **_features_rest**) also need to be rotated, so how to rotate the spherical harmonics?

**Comment by JonathonLuiten** [comment]
So in my work I turned the spherical harmonics off, not to deal with this, and also because they weren’t needed. 

However, if you want to do this, theoretically it is very easy (rotate the incoming directions used to calculate the SH), but maybe in the cuda code it is not super easy to implement. 

Note that there is a good chance this is not why your results look bad. Maybe the rotation of the quaternions was not correct also. I would recommend training a model with no SH, rotating that, and checking if that looks good first.

**Comment by RoyAmoyal** [comment]
> So in my work I turned the spherical harmonics off, not to deal with this, and also because they weren’t needed.
> 
> However, if you want to do this, theoretically it is very easy (rotate the incoming directions used to calculate the SH), but maybe in the cuda code it is not super easy to implement.
> 
> Note that there is a good chance this is not why your results look bad. Maybe the rotation of the quaternions was not correct also. I would recommend training a model with no SH, rotating that, and checking if that looks good first.

Is it still possible to turn off the spherical harmonics? I can't find the option for that in the 3DGS
